name: CI with Security Scans

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Run SAST with Semgrep
      run: semgrep scan --config auto

    - name: Run Trivy (IaC + Secrets)
      run: |
        trivy config .
        trivy fs --scanners secret .

